### ISSUE TITLE
Multiple errors.

### ISSUE THREAD

**Issue by techsideofficial** [natbtw/SRU18#1]
CRI runtime library is not compatible. Confirm the version number.
UnityEngine.Debug:LogError(Object)
CriWare:CheckBinaryVersionCompatibility() (at Assets/Plugins/CriWare/CriWare.cs:265)
CriWareInitializer:Awake() (at Assets/Plugins/CriWare/CriWareInitializer.cs:245)

EntryPointNotFoundException: criAtomUnity_SetConfigAdditionalParameters_PC
CriAtomPlugin.SetConfigAdditionalParameters_PC (Int64 buffering_time_pc) (at Assets/Plugins/CriWare/CriAtom/CriAtom.cs:126)
CriWareInitializer.Initialize () (at Assets/Plugins/CriWare/CriWareInitializer.cs:333)
CriWareInitializer.Awake () (at Assets/Plugins/CriWare/CriWareInitializer.cs:254)

NullReferenceException: Object reference not set to an instance of an object
GameObjectUtil.FindChildGameObject (UnityEngine.GameObject parent, System.String name) (at Assets/Scripts/GameObjectUtil.cs:59)
NetworkErrorWindow.Create (CInfo info) (at Assets/Scripts/NetworkErrorWindow.cs:219)
ErrorHandleRetry.StartErrorHandle () (at Assets/Scripts/ErrorHandleRetry.cs:73)
NetMonitor.EndMonitorBackward () (at Assets/Scripts/NetMonitor.cs:305)
AssetBundleLoader.AssetBundleResponseFailed (Message.MsgAssetBundleResponseFailed msg) (at Assets/Scripts/AssetBundleLoader.cs:288)
UnityEngine.GameObject:SendMessage(String, Object, SendMessageOptions)
AssetBundleRequest:Result() (at Assets/Scripts/AssetBundleRequest.cs:520)
<ExecuteRequest>c__Iterator0:MoveNext() (at Assets/Scripts/AssetBundleManager.cs:295)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

ArgumentException: The Object you want to instantiate is null.
UnityEngine.Object.CheckNullArgument (System.Object arg, System.String message) (at C:/buildslave/unity/build/Runtime/Export/UnityEngineObject.bindings.cs:381)
UnityEngine.Object.Instantiate (UnityEngine.Object original, Vector3 position, Quaternion rotation) (at C:/buildslave/unity/build/Runtime/Export/UnityEngineObject.bindings.cs:206)
UnityEngine.Object.Instantiate[GameObject] (UnityEngine.GameObject original, Vector3 position, Quaternion rotation) (at C:/buildslave/unity/build/Runtime/Export/UnityEngineObject.bindings.cs:285)
GeneralWindow.Create (CInfo info) (at Assets/Scripts/GeneralWindow.cs:749)
DebugTraceMenu.DebugButtonClickedCallback (System.String buttonName) (at Assets/Scripts/DebugTraceMenu.cs:63)
DebugTraceButton.OnGUI () (at Assets/Scripts/DebugTraceButton.cs:44)

[CRIWARE] ERROR: Atom library is already finalized.
UnityEngine.Debug:LogError(Object)
CriAtomPlugin:FinalizeLibrary() (at Assets/Plugins/CriWare/CriAtom/CriAtom.cs:232)
CriWareInitializer:OnDestroy() (at Assets/Plugins/CriWare/CriWareInitializer.cs:471)

**Comment by natstackzzz** [comment]
Unity ver?

**Comment by techsideofficial** [comment]
> Unity ver?

Same as the readme.

**Comment by natstackzzz** [comment]
Did you just download the repo or use git/github desktop?

**Comment by techsideofficial** [comment]
> Did you just download the repo or use git/github desktop?

I downloaded it using the green code button.

**Comment by techsideofficial** [comment]
@natstackzzz I used the green code dropdown

**Comment by natstackzzz** [comment]
use the tutorial that's in the readme

**Comment by techsideofficial** [comment]
@natstackzzz I did that. No difference.

**Comment by natstackzzz** [comment]
Dunno then, never encountered that when I originally messed with this.

**Comment by techsideofficial** [comment]
@natstackzzz This is really annoying, as it is the only semi-working decomp that I can find.

**Comment by natstackzzz** [comment]
ripp, also where does the error happen, while building or?

**Comment by techsideofficial** [comment]
@natstackzzz Just playing in the editor.

**Comment by natstackzzz** [comment]
they shouldn't really mean anything then, plus this project is nowhere near complete, might take a long ass time until EVERY bug or code error gets fixed
